apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitbank-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orbitbank
  template:
    metadata:
      labels:
        app: orbitbank
    spec:
      containers:
      - name: orbitbank-container
        image: orbitbank/app:latest

